# Sports14 Text/Image Feature Extraction

In [1]:

import os
import numpy as np
import pandas as pd

In [2]:
os.chdir('../data/grocery')
os.getcwd()

'/home/hun/MMRec_AlignRec/data/grocery'

## Load text data

In [3]:
i_id, desc_str = 'itemID', 'description'

file_path = './'
file_name = 'meta-grocery.csv'

meta_file = os.path.join(file_path, file_name)

df = pd.read_csv(meta_file)
df.sort_values(by=[i_id], inplace=True)

print('data loaded!')
print(f'shape: {df.shape}')

df[:3]

data loaded!
shape: (8713, 10)

,itemID,asin,description,title,imUrl,related,salesRank,categories,price,brand
0,0,616719923X,Green Tea Flavor Kit Kat have quickly become t...,Japanese Kit Kat Maccha Green Tea Flavor (5 Ba...,http://ecx.images-amazon.com/images/I/51LdEao6...,"{'also_bought': ['B00FD63L5W', 'B0047YG5UY', '...",{'Grocery & Gourmet Food': 37305},[['Grocery & Gourmet Food']],NaN,NaN
1,1,9742356831,Used to make various curry soups and stir fry ...,Mae Ploy Thai Green Curry Paste - 14 oz jar,http://ecx.images-amazon.com/images/I/41pQp67A...,"{'also_bought': ['B000EI2LLO', 'B000EICISA', '...",{'Grocery & Gourmet Food': 3434},[['Grocery & Gourmet Food']],7.23,Mae Ploy
2,2,B00004S1C5,"From Easter eggs to colorful cookies, Spectrum...","Ateco Food Coloring Kit, 6 colors",http://ecx.images-amazon.com/images/I/41F75K9F...,"{'also_bought': ['B0000CFMLT', 'B002PO3KBK', '...",{'Kitchen & Dining': 4494},"[['Grocery & Gourmet Food', 'Cooking & Baking'...",9.76,HIC Harold Import Co.

In [4]:

# sentences: title + brand + category + description | All have title + description

title_na_df = df[df['title'].isnull()]
print(title_na_df.shape)

desc_na_df = df[df['description'].isnull()]
print(desc_na_df.shape)

na_df = df[df['description'].isnull() & df['title'].isnull()]
print(na_df.shape)

na3_df = df[df['description'].isnull() & df['title'].isnull() & df['brand'].isnull()]
print(na3_df.shape)

na4_df = df[df['description'].isnull() & df['title'].isnull() & df['brand'].isnull() & df['categories'].isnull()]
print(na4_df.shape)

(13, 10)
(1204, 10)
(13, 10)
(13, 10)
(0, 10)

In [5]:

df[desc_str] = df[desc_str].fillna(" ")
df['title'] = df['title'].fillna(" ")
df['brand'] = df['brand'].fillna(" ")
df['categories'] = df['categories'].fillna(" ")

In [6]:
sentences = []
for i, row in df.iterrows():
    sen = row['title'] + ' ' + row['brand'] + ' '
    cates = eval(row['categories'])
    if isinstance(cates, list):
        for c in cates[0]:
            sen = sen + c + ' '
    sen += row[desc_str]
    sen = sen.replace('\n', ' ')

    sentences.append(sen)

sentences[:10]

["Japanese Kit Kat Maccha Green Tea Flavor (5 Bag) (4.91oz x 5)   Grocery & Gourmet Food Green Tea Flavor Kit Kat have quickly become the most sought after snack from Japan. Here are a limited supply of Maccha Green Tea flavored Kit Kat that you would not want to miss. These epic snacks have a sweet maccha green tea flavor mixed with creamy white chocolate, on a crispy wafer that Nestle's has perfected. Each bag contains 12 individually wrapped bars.",
 'Mae Ploy Thai Green Curry Paste - 14 oz jar Mae Ploy Grocery & Gourmet Food Used to make various curry soups and stir fry dishes. Mae Ploy Brand is recognized in Thailand as a high quality export product with rich taste and authentic flavor. Packed in convenient plastic tub with tighly sealed lid. All natural.',
 "Ateco Food Coloring Kit, 6 colors HIC Harold Import Co. Grocery & Gourmet Food Cooking & Baking Food Coloring From Easter eggs to colorful cookies, Spectrum's gel food colorings provide a wide range of decorative touches, with gorgeous colors and an enormous range of depth. Each color--black, blue, yellow, green, pink, and red--comes in a soft-sided plastic squeeze bottle that allows you to add a drop of color at a time to frostings and fillings. Paste colors are much more intense than more common liquid colors, and these will last through hundreds of fanciful cookies, providing stunning, professional-looking results.--Jill Lightner",
 'PowerBar Harvest Energy Bars, Double Chocolate Crisp, 2.29-Ounce Bars (Pack of 15) Powerbar Grocery & Gourmet Food  ',
 'Traditional Medicinals Breathe Easy, 16-Count Boxes (Pack of 6) Traditional Medicinals Grocery & Gourmet Food For nearly forty years, we&#x2019;ve been passionate about connecting people with plants and passing along the centuries-old wisdom of how to use them. So even though our packaging has changed, our aspirations remain the same: help you use plants to be healthy. Same great teas, same old us: devoted stewards of traditional herbal knowledge, practitioners of sustainable sourcing, meticulous judges of highest quality herbs, caring members of our communities, proud employee-owners of our independent company, herb nerds, and plant people who, without meaning to sound too hippie about it, feel like the plants are talking to us. We hope you will enjoy the fruits (or flowers, roots and leaves) of our labor',
 "PowerBar ProteinPlus High Protein Bar, Vanilla Yogurt, 2.75-Ounce Bars (Pack of 12)   Grocery & Gourmet Food The PowerBar ProteinPlus Protein Bar is a great choice for use before and after activities like weightlifting and strength training where protein intake has been shown to help improve growth and reduce breakdown of muscle. It also helps build a lean body and provides sustained energy for athletes who want more protein. This PowerBar ProteinPlus Protein Bar contains 23 grams of PowerBar TriSource protein blend, a proprietary blend of whey, soy and casein proteins for a steady supply of muscle-building amino acids. To help support muscle growth and repair and to fuel exercise, eat one half to a whole bar before and/or after strength training workouts.ProteinPlus Protein BarAt a Glance:Contains 23 grams of TriSource protein blendHelps build a lean body and provide sustained energyNo preservatives or artificial flavors100 percent daily value of vitamins C and E and eight B-complex vitaminsEat half to a whole bar before strength trainingPowerBar TriSource blend provides a steady supply of muscle-building amino acids.Helps build a lean body and provides energy for athletes who want more protein.Reach Your Excercise Goals FasterWhether you do endurance exercise, play team sports, or strength train, consuming protein after a workout can help you reach your training goals faster. Protein supplies necessary amino acids to help rebuild and repair muscle tissue. Although protein requirements may vary between individuals, for example due to differences in body size or activity level, in general look to consume a minimum of 15 to 25 grams of protein within an hour after exercise to maximize the muscle rebuilding process.Convenient Source of High-Quality ProteinThe PowerBar ProteinPlus Protein Bar was developed according to the needs of world-class athletes and others who want a convenient, great tasting source of high quality protein. Each bar contains approximately 52 percent of calories from carbohydrates, 33 percent from protein, and 15 percent from fat. As with other PowerBar products, PowerBar ProteinPlus protein bar is a great addition to a healthy diet to help achieve optimal performance.This bar contains 23 grams of PowerBar TriSource protein blend, a combination of three protein sources: whey protein isolate, calcium caseinate, and soy protein isolate. It supplies the same amount of protein as one 3-ounce chicken breast, three cups of 2 percent milk, one 3.5-ounce serving of tuna, and one 4-ounce serving of porterhouse steak.What's in the BoxPowerBar ProteinPlus Protein Bar, Vanilla Yogurt (Pack of 12).ProteinPlus Protein BarsTrademark Information:PowerBar ProteinPlus&reg; Protein Bar",
 'American Outdoor Products Astronaut Ice Cream (Pack of 10) American Outdoor Products Grocery & Gourmet Food Funkyfoodshop is the #1 seller of space food on the Internet and this is our bestselling item: Astronaut Ice Cream. You receive 10 Neapolitan (Strawberry, Vanilla and Chocolate) ready-to-eat freeze-dried bars. This is the kind you find at science museums at two or three times the price. Originally developed for the early Apollo missions, food is frozen to -40 degrees F and then vacuum dried and placed in a special foil pouch. These products are manufactured by the same company that supplies freeze-dried foods to NASA for the Space Shuttle missions. Ingredients include milk, cream, nonfat milk, sugar, corn syrup, strawberries, cocoa processed with alkali, whey solids, contains less than 1% mono and diglycerides, guar gum, locust bean gum, carrageenan, vanilla extract, natural flavors. We provide fast, reliable shipping. We always have the products in stock and will turn around your orders fast via Priority Mail.',
 "Melitta Cone Coffee Filters, Natural Brown, No. 1, 40-Count Filters (Pack of 12) Melitta Grocery & Gourmet Food Thicker, textured, high quality paper with patented flavor enhancing micro perforations, traps harmful oils & bitter sediment to deliver the full taste and aroma of your coffee to your cup! An added extra crimp for additional strength, prevents filter bursts and provide safe, easy disposal.   Made from unbleached paper pulp for today's demand for environmentally safe, natural products, Melitta makes annual contributions to the American Forests Global Releaf fund.",
 'Panda All Natural Soft Licorice 7 oz Pkg Panda Grocery & Gourmet Food Licorice (Black) Chews by Panda Licorice 7 oz Box PANDA ALL NATURAL - THE REAL TASTE OF LICORICE The strong-flavoured high-quality Panda All Naturall Licorice is the Rolls Royce of licorices. The product is manufactured from natural ingredients without preservatives and using time-honoured manufacturing methods. It forms a natural alternative for those with a passion for licorice and has been the most successful all natural licorice in the world since 1977 as the market leader in its sector of the Health Food Industries in Great Britain and the United States. Panda - A fresh success Panda Licorice comes in a package that has been developed specifically to keep the product soft fresh and delicious tasting. Pandas success around the world is based on the freshness and unique consistency of the product. The unique Real taste of Licorice Premium quality soft licorice All Natural ingredients No added colours No added salt No artificial flavours 99 fat free No preservatives Kosher certified',
 'Cafix Coffee Substitute Crystals Jar 7.05 Ounces Cafix Grocery & Gourmet Food Beverages Coffee Coffee Substitutes Cafix - Instant Beverage Crystals Coffee Substitute All Natural - 7.05 oz. (200 g) Cafix All Natural Instant Beverage Crystals are a 100% naturally caffeine free coffee substitute. Cafix Crystals offer a rich, robust taste yet none of the caffeine or acidity found in coffee or tea. Unlike decaffeinated beverages, Cafix Crystals do not undergo additional processing due to the naturally caffeine free ingredients. Cafix Instant Beverage Features: No Cholesterol Low Sodium No Trans Fat As more and more people choose to eliminate caffeine from their diets, Cafix coffee substitute is the perfect alternative. It\'s everything you would like an instant hot caffeine free drink to be. Cafix coffee substitute offers a rich, coffee-like flavor yet none of the caffeine or acidity found in coffee or tea which can stimulate the nervous system or cause an upset stomach. Cafix coffee substitute is not a decaffeinated product but a healthful coffee alternative that is a blend of all natural, caffeine free ingredients, so the whole family can enjoy it...anytime. About Trans FatWhen it comes to fat, trans fat is considered by some doctors to be the worst type of fat. Unlike other fats, trans fat also called trans-fatty acids both raises your "bad" (LDL) cholesterol and lowers your "good" (HDL) cholesterol. A high LDL cholesterol level in combination with a low HDL cholesterol level increases your risk of heart disease, the leading killer of men and women. Here\'s some information about trans fat and how to avoid it. What is Trans Fat?Trans fat is made by adding hydrogen to vegetable oil through a process called hydrogenation, which makes the oil less likely to spoil. Using trans fats in the manufacturing of foods helps foods stay fresh longer, have a longer shelf life and have a less greasy feel. Scientists aren\'t sure exactly why, but the addition of hydrogen to oil increases your cholesterol more than do other types of fats.']

In [7]:

course_list = df[i_id].tolist()
#sentences = df[desc_str].tolist()

assert course_list[-1] == len(course_list) - 1

In [8]:
# should `pip install sentence_transformers` first
from sentence_transformers import SentenceTransformer

model = SentenceTransformer('all-MiniLM-L6-v2')

sentence_embeddings = model.encode(sentences)
print('text encoded!')

assert sentence_embeddings.shape[0] == df.shape[0]
np.save(os.path.join(file_path, 'text_feat.npy'), sentence_embeddings)
print('done!')

/home/hun/miniconda3/envs/ipy/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/hun/miniconda3/envs/ipy/lib/python3.10/site-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/hun/miniconda3/envs/ipy/lib/python3.10/site-packages/huggingface_hub/file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

text encoded!
done!

In [9]:
sentence_embeddings[:10]

array([[ 0.01657731, -0.00646653,  0.05703938, ..., -0.04410642,
        -0.01208084, -0.02984802],
       [-0.03333354, -0.03070537,  0.06911523, ...,  0.0018233 ,
         0.0642586 , -0.00366994],
       [-0.03570388, -0.01664365,  0.00453851, ...,  0.01162007,
         0.00400354, -0.02355654],
       ...,
       [-0.00148825,  0.02671757,  0.06408443, ..., -0.03550781,
         0.12077958,  0.00370013],
       [-0.05085435, -0.13789088, -0.03795417, ..., -0.0008477 ,
         0.11135017,  0.04063827],
       [ 0.0018889 , -0.05882647,  0.05027296, ..., -0.09206817,
         0.06217723, -0.11353085]], shape=(10, 384), dtype=float32)

In [10]:
load_txt_feat = np.load('text_feat.npy', allow_pickle=True)
print(load_txt_feat.shape)
load_txt_feat[:10]

(8713, 384)

array([[ 0.01657731, -0.00646653,  0.05703938, ..., -0.04410642,
        -0.01208084, -0.02984802],
       [-0.03333354, -0.03070537,  0.06911523, ...,  0.0018233 ,
         0.0642586 , -0.00366994],
       [-0.03570388, -0.01664365,  0.00453851, ...,  0.01162007,
         0.00400354, -0.02355654],
       ...,
       [-0.00148825,  0.02671757,  0.06408443, ..., -0.03550781,
         0.12077958,  0.00370013],
       [-0.05085435, -0.13789088, -0.03795417, ..., -0.0008477 ,
         0.11135017,  0.04063827],
       [ 0.0018889 , -0.05882647,  0.05027296, ..., -0.09206817,
         0.06217723, -0.11353085]], shape=(10, 384), dtype=float32)

# Image encoder (V0)，following LATTICE, averaging over for missed items

In [11]:
df[:5]

,itemID,asin,description,title,imUrl,related,salesRank,categories,price,brand
0,0,616719923X,Green Tea Flavor Kit Kat have quickly become t...,Japanese Kit Kat Maccha Green Tea Flavor (5 Ba...,http://ecx.images-amazon.com/images/I/51LdEao6...,"{'also_bought': ['B00FD63L5W', 'B0047YG5UY', '...",{'Grocery & Gourmet Food': 37305},[['Grocery & Gourmet Food']],NaN,
1,1,9742356831,Used to make various curry soups and stir fry ...,Mae Ploy Thai Green Curry Paste - 14 oz jar,http://ecx.images-amazon.com/images/I/41pQp67A...,"{'also_bought': ['B000EI2LLO', 'B000EICISA', '...",{'Grocery & Gourmet Food': 3434},[['Grocery & Gourmet Food']],7.23,Mae Ploy
2,2,B00004S1C5,"From Easter eggs to colorful cookies, Spectrum...","Ateco Food Coloring Kit, 6 colors",http://ecx.images-amazon.com/images/I/41F75K9F...,"{'also_bought': ['B0000CFMLT', 'B002PO3KBK', '...",{'Kitchen & Dining': 4494},"[['Grocery & Gourmet Food', 'Cooking & Baking'...",9.76,HIC Harold Import Co.
3,3,B0000531B7,,"PowerBar Harvest Energy Bars, Double Chocolate...",http://ecx.images-amazon.com/images/I/519SuVj1...,"{'also_bought': ['B000EC63PU', 'B00DZGEY44', '...",{'Grocery & Gourmet Food': 2858},[['Grocery & Gourmet Food']],24.75,Powerbar
4,4,B00005344V,"For nearly forty years, we&#x2019;ve been pass...","Traditional Medicinals Breathe Easy, 16-Count ...",http://ecx.images-amazon.com/images/I/51H54cd-...,"{'also_bought': ['B0009F3POE', 'B0009F3POO', '...",{'Grocery & Gourmet Food': 5034},[['Grocery & Gourmet Food']],21.74,Traditional Medicinals

In [12]:
import array

def readImageFeatures(path):
  f = open(path, 'rb')
  while True:
    asin = f.read(10).decode('UTF-8')
    if asin == '': break
    a = array.array('f')
    a.fromfile(f, 4096)
    yield asin, a.tolist()

In [13]:

img_data = readImageFeatures("image_features_Grocery_and_Gourmet_Food.b")
item2id = dict(zip(df['asin'], df['itemID']))

feats = {}
avg = []
for d in img_data:
    if d[0] in item2id:
        feats[int(item2id[d[0]])] = d[1]
        avg.append(d[1])
avg = np.array(avg).mean(0).tolist()

ret = []
non_no = []
for i in range(len(item2id)):
    if i in feats:
        ret.append(feats[i])
    else:
        non_no.append(i)
        ret.append(avg)

print('# of items not in processed image features:', len(non_no))
assert len(ret) == len(item2id)
np.save('image_feat.npy', np.array(ret))
np.savetxt("missed_img_itemIDs.csv", non_no, delimiter =",", fmt ='%d')
print('done!')

# of items not in processed image features: 97
done!